//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoistLib.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoistLib.Language.AppResources_en-US", typeof(AppResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already registered with us..
        /// </summary>
        internal static string error_ALREADY_REGISTRED {
            get {
                return ResourceManager.GetString("error_ALREADY_REGISTRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email isn&apos;t valid..
        /// </summary>
        internal static string error_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("error_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 5 chars long..
        /// </summary>
        internal static string error_TOO_SHORT_PASSWORD {
            get {
                return ResourceManager.GetString("error_TOO_SHORT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something strange happened. Please try again or contact us..
        /// </summary>
        internal static string error_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("error_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        internal static string general_confirm {
            get {
                return ResourceManager.GetString("general_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some problem with your internet connection. Could you try again?.
        /// </summary>
        internal static string general_connection_canceled {
            get {
                return ResourceManager.GetString("general_connection_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running on offline mode. Please check your internet connection..
        /// </summary>
        internal static string general_no_connection {
            get {
                return ResourceManager.GetString("general_no_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string general_search {
            get {
                return ResourceManager.GetString("general_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data.
        /// </summary>
        internal static string loading_data {
            get {
                return ResourceManager.GetString("loading_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string login_about_label {
            get {
                return ResourceManager.GetString("login_about_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string login_action_button {
            get {
                return ResourceManager.GetString("login_action_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string login_email_label {
            get {
                return ResourceManager.GetString("login_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect with Google.
        /// </summary>
        internal static string login_google_button {
            get {
                return ResourceManager.GetString("login_google_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or you can sign in with your Google account.
        /// </summary>
        internal static string login_google_login {
            get {
                return ResourceManager.GetString("login_google_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting access with your Google account.
        /// </summary>
        internal static string login_google_login_loading {
            get {
                return ResourceManager.GetString("login_google_login_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string login_logging {
            get {
                return ResourceManager.GetString("login_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signup.
        /// </summary>
        internal static string login_newuser_label {
            get {
                return ResourceManager.GetString("login_newuser_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_password_label {
            get {
                return ResourceManager.GetString("login_password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string signup_email {
            get {
                return ResourceManager.GetString("signup_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string signup_name {
            get {
                return ResourceManager.GetString("signup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string signup_password {
            get {
                return ResourceManager.GetString("signup_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (retype your password for confirmation).
        /// </summary>
        internal static string signup_password_confirm {
            get {
                return ResourceManager.GetString("signup_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be at least 5 characters..
        /// </summary>
        internal static string signup_password_min {
            get {
                return ResourceManager.GetString("signup_password_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your timezone.
        /// </summary>
        internal static string signup_select_timezone {
            get {
                return ResourceManager.GetString("signup_select_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering your new account.
        /// </summary>
        internal static string signup_signing {
            get {
                return ResourceManager.GetString("signup_signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You was registered successfuly..
        /// </summary>
        internal static string signup_success {
            get {
                return ResourceManager.GetString("signup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string signup_timezone {
            get {
                return ResourceManager.GetString("signup_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        internal static string signup_title {
            get {
                return ResourceManager.GetString("signup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match. Try again..
        /// </summary>
        internal static string singup_password_noteual {
            get {
                return ResourceManager.GetString("singup_password_noteual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timezone.
        /// </summary>
        internal static string timezone_title {
            get {
                return ResourceManager.GetString("timezone_title", resourceCulture);
            }
        }
    }
}
