//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoistLib.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoistLib.Language.AppResources_pt-BR", typeof(AppResources_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu e-mail já está registrado conosco..
        /// </summary>
        internal static string error_ALREADY_REGISTRED {
            get {
                return ResourceManager.GetString("error_ALREADY_REGISTRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        internal static string error_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("error_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos 5 caracteres..
        /// </summary>
        internal static string error_TOO_SHORT_PASSWORD {
            get {
                return ResourceManager.GetString("error_TOO_SHORT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops, algo estranho aconteceu. Por favor, tente novamente ou entre em contato conosco..
        /// </summary>
        internal static string error_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("error_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmar.
        /// </summary>
        internal static string general_confirm {
            get {
                return ResourceManager.GetString("general_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um problema com sua conexão de internet. Você poderia tentar novamente?.
        /// </summary>
        internal static string general_connection_canceled {
            get {
                return ResourceManager.GetString("general_connection_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está rodando em modo offline. Por favor, verifique sua conexão com a internet..
        /// </summary>
        internal static string general_no_connection {
            get {
                return ResourceManager.GetString("general_no_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buscar.
        /// </summary>
        internal static string general_search {
            get {
                return ResourceManager.GetString("general_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando dados.
        /// </summary>
        internal static string loading_data {
            get {
                return ResourceManager.GetString("loading_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sobre.
        /// </summary>
        internal static string login_about_label {
            get {
                return ResourceManager.GetString("login_about_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string login_action_button {
            get {
                return ResourceManager.GetString("login_action_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string login_email_label {
            get {
                return ResourceManager.GetString("login_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conectar usando o Google.
        /// </summary>
        internal static string login_google_button {
            get {
                return ResourceManager.GetString("login_google_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou você pode entrar com sua conta do Google.
        /// </summary>
        internal static string login_google_login {
            get {
                return ResourceManager.GetString("login_google_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtendo acesso com sua conta no Google.
        /// </summary>
        internal static string login_google_login_loading {
            get {
                return ResourceManager.GetString("login_google_login_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logando.
        /// </summary>
        internal static string login_logging {
            get {
                return ResourceManager.GetString("login_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrar.
        /// </summary>
        internal static string login_newuser_label {
            get {
                return ResourceManager.GetString("login_newuser_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string login_password_label {
            get {
                return ResourceManager.GetString("login_password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string signup_email {
            get {
                return ResourceManager.GetString("signup_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nome.
        /// </summary>
        internal static string signup_name {
            get {
                return ResourceManager.GetString("signup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string signup_password {
            get {
                return ResourceManager.GetString("signup_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha (redigite sua senha para confirmação).
        /// </summary>
        internal static string signup_password_confirm {
            get {
                return ResourceManager.GetString("signup_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha deve possuir no mínimo 5 caracteres..
        /// </summary>
        internal static string signup_password_min {
            get {
                return ResourceManager.GetString("signup_password_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas digitas não conferem. Tente novamente..
        /// </summary>
        internal static string signup_password_notequal {
            get {
                return ResourceManager.GetString("signup_password_notequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o seu fuso horário.
        /// </summary>
        internal static string signup_select_timezone {
            get {
                return ResourceManager.GetString("signup_select_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrando sua nova conta.
        /// </summary>
        internal static string signup_signing {
            get {
                return ResourceManager.GetString("signup_signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu cadastro foi realizado com sucesso..
        /// </summary>
        internal static string signup_success {
            get {
                return ResourceManager.GetString("signup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuso horário.
        /// </summary>
        internal static string signup_timezone {
            get {
                return ResourceManager.GetString("signup_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registrar.
        /// </summary>
        internal static string signup_title {
            get {
                return ResourceManager.GetString("signup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuso horário.
        /// </summary>
        internal static string timezone_title {
            get {
                return ResourceManager.GetString("timezone_title", resourceCulture);
            }
        }
    }
}
